//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLA_Jobs.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Vacante
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Company { get; set; }
        public string Direccion_url { get; set; }
        public string Logo { get; set; }
        public HttpPostedFileBase LogoFile { get; set; }
        public string Posicion { get; set; }
        public string Ubicacion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string CorreoAplicar { get; set; }
        public int Categoria { get; set; }
        public string EmailUsuario { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
    }
}
